@currentUser=yu.shen

### Home
GET http://localhost:8080/ 
Authorization: Basic {{currentUser}} 123456

### Create Projects
POST http://localhost:8080/projects
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json

{
    "name": "Smart Project Management DEV",
    "members":["huanhuan.dong","yongjian.sha"]
}

### View my Projects
GET http://localhost:8080/projects/search/findMyProjects?me={{currentUser}}&status=INIT,RUNNING,STOP
Authorization: Basic {{currentUser}} 123456

### List Projects
GET http://localhost:8080/projects
Authorization: Basic {{currentUser}} 123456


### Get message 
http://localhost:8080/messages/search/findByReceiver?upn=huanhuan.dong
Authorization: Basic {{currentUser}} 123456

### Get Event 
http://localhost:8080/events
Authorization: Basic {{currentUser}} 123456

### Update Project
PATCH  http://localhost:8080/projects/4781467596765545898
Authorization: Basic {{currentUser}} 123456

{
    "name": "New project 333",
    "members":["huanhuan.dong"]
}

### Cancel a project

PATCH  http://localhost:8080/projects/3394581405255253323
Authorization: Basic {{currentUser}} 123456

{
    "status":"STOP"
}




