@currentUser=yu.shen
@currentProject=472927559347452297

### Ping
GET http://localhost:8080/ping
Authorization: Basic {{currentUser}} 123456

### Home
GET http://localhost:8080/ 
Authorization: Basic {{currentUser}} 123456

### Create Projects
POST http://localhost:8080/projects
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json

{
    "name": "Smart Project Management DEV",
    "members":["huanhuan.dong","yongjian.sha"]
}

### View my Projects
GET http://localhost:8080/projects/search/findMyProjects?me={{currentUser}}&status=INIT,RUNNING
Authorization: Basic {{currentUser}} 123456

### View a Projects
GET http://localhost:8080/projects/{{currentProject}}
Authorization: Basic {{currentUser}} 123456

### List Projects
GET http://localhost:8080/projects
Authorization: Basic {{currentUser}} 123456


### Get message 
http://localhost:8080/messages/search/findByReceiver?upn=huanhuan.dong
Authorization: Basic {{currentUser}} 123456

### Get Event 
http://localhost:8080/events
Authorization: Basic {{currentUser}} 123456

### Update Project
PATCH http://localhost:8080/projects/{{currentProject}}
Authorization: Basic {{currentUser}} 123456

{
    "name": "New project 333",
    "members":["huanhuan.dong"]
}

### Cancel a project
POST http://localhost:8080/projects/{{currentProject}}/actions/cancel
Authorization: Basic {{currentUser}} 123456

### Delete a project
DELETE http://localhost:8080/projects/{{currentProject}}
Authorization: Basic {{currentUser}} 123456

### Add Phase (Planning)
POST  http://localhost:8080/projects/{{currentProject}}/phases/actions/append
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json

{
    "name": "Planning",
    "plannedStartDate": "2020-09-01",
    "plannedEndDate": "2020-10-01"
}

### Add Phase (GOGOGO)
POST  http://localhost:8080/projects/{{currentProject}}/phases/actions/append
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json

{
    "name": "GoGoGo",
    "plannedEndDate": "2020-10-30"
}

### Add Phase (error)
POST  http://localhost:8080/projects/{{currentProject}}/phases/actions/append
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json

{
    "name": "Testing2",
    "plannedEndDate": "2020-11-20"
}

@firstPhase=8813888436995375126
### Delete phase
DELETE http://localhost:8080/phases/{{firstPhase}}
Authorization: Basic {{currentUser}} 123456
Content-Type: application/json



